In [1]:
%load_ext autoreload
%autoreload 
%reload_ext autoreload

In [1]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support
from features import topological_features, aggregate_features, get_vars, extract_features
import pickle
import rolx
import numpy as np
import utils
import random

def get_scores(train_pred, train_true, val_pred, val_true, test_pred, test_true):
    train_accuracy = np.mean(train_pred == train_true)
    print (train_accuracy)

    train_f1 =  precision_recall_fscore_support(train_true, train_pred)
    print (train_f1[0][1])
    print (train_f1[1][1])
    print (train_f1[2][1])
    
    val_accuracy = np.mean(val_pred == val_true)
    print (val_accuracy)
    
    val_f1 =  precision_recall_fscore_support(val_true, val_pred)
    print (val_f1[0][1])
    print (val_f1[1][1])
    print (val_f1[2][1])

    test_accuracy = np.mean(test_pred == test_true)
    print (test_accuracy)
    
    test_f1 =  precision_recall_fscore_support(test_true, test_pred)
    print (test_f1[0][1])
    print (test_f1[1][1])
    print (test_f1[2][1])


In [3]:
def get_rolx(fname, fname_extended, roles=3):
    G, dict_to_graph, graph_to_dict = rolx.load_graph_igraph(fname, fname_extended)
    H, R = rolx.extract_rolx_roles(G, roles)
    print(H.shape, R.shape)
    H.tolist()

    adj_mat = G.get_adjacency()
    _, video_dict_list, graph_to_dict, neighbors, fields = get_vars(fname, fname_extended)
    # np.save('rolx_features', H)
    # H = np.load('rolx_features.npy')
    
    return adj_mat, H, video_dict_list, graph_to_dict, neighbors, fields

def get_features(adj_mat, H, video_dict_list, graph_to_dict, neighbors, fields, agg_flag=False):
    X = []
    y = []
    pos_data = []
    neg_data = []
    for row in range(adj_mat.shape[0]):
        H_row = np.array(H[row]).flatten()
        for col in range(adj_mat.shape[1]):
            H_total = np.array(H[col][0]).flatten() + H_row
            # print 'pre concatenated', type(H_total), H_total

            # flag for adding into agg and topo features
            if agg_flag:
                local_features = extract_features(video_dict_list, graph_to_dict, neighbors, fields, row, col) 
                # skip if doesnt exist
                if not local_features:
                    continue

                H_total = np.concatenate([H_total, local_features]) 
                # print 'after concatenated', type(H_total), H_total

            if adj_mat[row][col] > 0:
                pos_data.append((H_total, adj_mat[row][col]))
            else:
                neg_data.append((H_total, adj_mat[row][col]))
    
    return pos_data, neg_data

In [4]:
fname = './dataset/0222/0.txt'
fname_extended = './dataset/0222/1.txt'

adj_mat, H, video_dict_list, graph_to_dict, neighbors, fields = get_rolx(fname, fname_extended)
pos_data, neg_data = get_features(adj_mat, H, video_dict_list, graph_to_dict, neighbors, fields)

Creating Vertex Features matrix
V is a 3356 by 485 matrix.
Node-role matrix is of dimensions 3356 by 3
[[0.         0.0199036  0.00744173]
 [0.         0.02791589 0.03119776]
 [0.         0.01000588 0.01839252]
 ...
 [0.         0.00740323 0.01428153]
 [0.         0.00737681 0.01464255]
 [0.         0.00737681 0.01464255]]
[[3.97698502e+04 1.14131367e-01 2.00000000e+01 ... 1.14373638e-03
  1.14373638e-03 2.00000000e+01]
 [6.67290721e+04 1.22706739e-01 4.00000000e+00 ... 2.08546433e-04
  2.08546433e-04 4.00000000e+00]
 [0.00000000e+00 1.11362115e-01 3.00000000e+00 ... 1.85490526e-04
  1.85490526e-04 3.00000000e+00]
 ...
 [3.33333333e-01 5.58823529e-01 4.00000000e+00 ... 2.06357331e-04
  2.06357331e-04 4.00000000e+00]
 [0.00000000e+00 5.58823529e-01 4.00000000e+00 ... 1.98521122e-04
  1.98521122e-04 4.00000000e+00]
 [0.00000000e+00 5.58823529e-01 4.00000000e+00 ... 1.98521122e-04
  1.98521122e-04 4.00000000e+00]]
[[0.00408327 0.         0.01162663 0.         0.         0.
  0.         0.

In [5]:
fname_test = './dataset/080327/0.txt'
fname_test_extended = './dataset/080327/1.txt'

adj_mat_test, H_test, video_dict_list_test, graph_to_dict_test, neighbors_test, fields_test = get_rolx(fname_test, fname_test_extended)
pos_data_test, neg_data_test = get_features(adj_mat_test, H_test, video_dict_list_test, graph_to_dict_test, neighbors_test, fields_test)

Creating Vertex Features matrix
V is a 4330 by 408 matrix.


c:\Users\Bao Tran\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\decomposition\_nmf.py:1770: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


Node-role matrix is of dimensions 4330 by 3
[[0.19925109 0.16108741 0.00058692]
 [0.07929716 0.13149653 0.05354079]
 [0.19925109 0.16108741 0.00058692]
 ...
 [0.09832276 0.13102633 0.05499859]
 [0.1229468  0.13840692 0.06407499]
 [0.08100141 0.12920092 0.08111056]]
[[1.27952413e+04 8.77933545e-02 2.00000000e+01 ... 3.99064480e-04
  3.99064480e-04 2.00000000e+01]
 [7.14285714e-01 8.07364935e-02 1.00000000e+01 ... 2.10219785e-04
  2.10219785e-04 1.00000000e+01]
 [1.27952413e+04 8.77933545e-02 2.00000000e+01 ... 3.99064480e-04
  3.99064480e-04 2.00000000e+01]
 ...
 [1.06668301e+01 5.27777778e-01 1.10000000e+01 ... 2.52185559e-04
  2.52185559e-04 1.10000000e+01]
 [1.25640720e+00 5.50724638e-01 1.20000000e+01 ... 2.52082882e-04
  2.52082882e-04 1.20000000e+01]
 [0.00000000e+00 5.06666667e-01 9.00000000e+00 ... 1.95368248e-04
  1.95368248e-04 9.00000000e+00]]
[[0.         0.         0.02484641 0.         0.         0.
  0.         0.0248456 ]
 [0.03682037 0.12328192 0.128708   0.15966354 0.1

In [6]:
def split_data_balanced(pos_data, neg_data):
    # creates positive and negative dataset for more uniform distribution of data
    X = [pos_data[i][0] for i in range(len(pos_data))]
    Y = [pos_data[i][1] for i in range(len(pos_data))]

    random_indices = sorted(random.sample(range(len(neg_data)), len(X)))
    X_neg = [neg_data[i][0] for i in random_indices]
    Y_neg = [neg_data[i][1] for i in random_indices]

    X.extend(X_neg)
    Y.extend(Y_neg)

    X_array = np.array(X)
    Y_array = np.array(Y)
    
    print (X_array.shape, Y_array.shape)
    from sklearn.preprocessing import normalize
    # change this line to change the number of features
    X_array = X_array[:, np.r_[:3]]
    print (X_array.shape)

    # runs training by splitting train/test sets
    return train_test_split(X_array, Y_array, test_size=0.2, random_state=42)

In [9]:
def split_data(pos_data, neg_data):
    # runs training by splitting train/test sets
    X = [pos_data[i][0] for i in range(len(pos_data))]
    Y = [pos_data[i][1] for i in range(len(pos_data))]

    X_neg = [neg_data[i][0] for i in range(len(neg_data))]
    Y_neg = [neg_data[i][1] for i in range(len(neg_data))]

    X.extend(X_neg)
    Y.extend(Y_neg)

    X_array = np.array(X)
    Y_array = np.array(Y)
#     X_array = X_array[:, np.r_[:3]]

    X_train, X_test, y_train, y_test = train_test_split(X_array, Y_array, test_size=0.01, random_state=42)

    test_zero_vals = np.argwhere(y_test == 0)
    test_one_vals = np.argwhere(y_test == 1)
    print ('test zero vals', len(test_zero_vals), 'test one vals', len(test_one_vals))

    zero_vals = np.argwhere(y_train == 0)
    one_vals = np.argwhere(y_train == 1)
    random_indices = zero_vals[sorted(random.sample(range(len(zero_vals)), len(one_vals)))]
    random_indices = np.concatenate([random_indices, one_vals]).reshape(-1)

    X_train = X_train[random_indices]
    y_train = y_train[random_indices]
    print (X_train.shape, y_train.shape)

    train_zero_vals = np.argwhere(y_train == 0)
    train_one_vals = np.argwhere(y_train == 1)
    print ('train zero vals', len(train_zero_vals), 'train one vals', len(train_one_vals))
    return X_train, X_test, y_train, y_test

In [10]:
X_train, X_val, y_train, y_val = split_data(pos_data, neg_data)
_, X_test, _, y_test = split_data(pos_data_test, neg_data_test)

test zero vals 112185 test one vals 442
(83028, 3) (83028,)
train zero vals 41514 train one vals 41514
test zero vals 187235 test one vals 254
(57420, 3) (57420,)
train zero vals 28710 train one vals 28710


In [15]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, max_depth=2,
                              random_state=0)
clf.fit(X_train, y_train)

print ('---random forest---')
train_predictions = clf.predict(X_train)
val_predictions = clf.predict(X_val)
test_predictions = clf.predict(X_test)

get_scores(train_predictions, y_train, val_predictions, y_val, test_predictions, y_test)
np.savetxt('results/random_forest.txt', test_predictions)

---random forest---
0.6017247193717782
0.7134768981902739
0.3399816929228694
0.4605194466196815
0.863763895301346
0.010382441845183336
0.3574660633484163
0.020178799489144316
0.4405965149955464
0.0017714285714285714
0.7322834645669292
0.003534307484751173


c:\Users\Bao Tran\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [16]:
clf = LogisticRegression(random_state=0, solver='lbfgs').fit(X_train, y_train)
print ('---logistic regression---')
# makes predictions
train_predictions = clf.predict(X_train)
val_predictions = clf.predict(X_val)
test_predictions = clf.predict(X_test)

get_scores(train_predictions, y_train, val_predictions, y_val, test_predictions, y_test)
np.savetxt('results/logistic_regression.txt', test_predictions)

---logistic regression---
0.5864045864045864
0.6199023933680974
0.446716770246182
0.5192496150076998
0.7287441843946443
0.006717127035617157
0.4638009049773756
0.013242466328606957
0.6888670802020386
0.002484152818228542
0.5708661417322834
0.004946779475982533


c:\Users\Bao Tran\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [17]:
from sklearn import svm

svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)

print ('---svm_rbf---')
# makes predictions
train_predictions = clf.predict(X_train)
val_predictions = clf.predict(X_val)
test_predictions = clf.predict(X_test)

train_preds = [pred > 0.5 for pred in train_predictions]
test_preds = [pred > 0.5 for pred in test_predictions]

get_scores(train_predictions, y_train, val_predictions, y_val, test_predictions, y_test)
# np.savetxt('results/svm_rbf.txt', test_predictions)

---svm_rbf---
0.5864045864045864
0.6199023933680974
0.446716770246182
0.5192496150076998
0.7287441843946443
0.006717127035617157
0.4638009049773756
0.013242466328606957
0.6888670802020386
0.002484152818228542
0.5708661417322834
0.004946779475982533


c:\Users\Bao Tran\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [18]:
from sklearn import svm

svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

print ('---svm linear---')
# makes predictions
train_predictions = clf.predict(X_train)
val_predictions = clf.predict(X_val)
test_predictions = clf.predict(X_test)

train_preds = [pred > 0.5 for pred in train_predictions]
test_preds = [pred > 0.5 for pred in test_predictions]

get_scores(train_predictions, y_train, val_predictions, y_val, test_predictions, y_test)
# np.savetxt('results/svm_linear.txt', test_predictions)

---svm linear---
0.5864045864045864
0.6199023933680974
0.446716770246182
0.5192496150076998
0.7287441843946443
0.006717127035617157
0.4638009049773756
0.013242466328606957
0.6888670802020386
0.002484152818228542
0.5708661417322834
0.004946779475982533


c:\Users\Bao Tran\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [21]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)

print ('---knn---')
# makes predictions
train_predictions = clf.predict(X_train)
val_predictions = clf.predict(X_val)
test_predictions = clf.predict(X_test)

train_preds = [pred > 0.5 for pred in train_predictions]
test_preds = [pred > 0.5 for pred in test_predictions]

get_scores(train_predictions, y_train, val_predictions, y_val, test_predictions, y_test)
np.savetxt('results/knn.txt', test_predictions)

---knn---
0.9592667533844005
0.9251817492529325
0.9993496169966758
0.960836537125388
0.8559594417018859
0.024983444705315754
0.9389140271493213
0.0486717879551985
0.7961960435012188
0.0019942795665065993
0.2992125984251969
0.003962151030941272


c:\Users\Bao Tran\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [22]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X_train, y_train)

print ('---naive bayes---')
# makes predictions
train_predictions = clf.predict(X_train)
val_predictions = clf.predict(X_val)
test_predictions = clf.predict(X_test)

train_preds = [pred > 0.5 for pred in train_predictions]
test_preds = [pred > 0.5 for pred in test_predictions]

get_scores(train_predictions, y_train, val_predictions, y_val, test_predictions, y_test)
np.savetxt('results/naive_bayes.txt', test_predictions)

---naive bayes---
0.5289781760369996
0.5216164738014807
0.6992580816110228
0.5975135335405388
0.3606740774940512
0.004060984060984061
0.6628959276018099
0.00807251487767247
0.2321042834512958
0.0017403966162806823
0.9881889763779528
0.0034746736437005965


c:\Users\Bao Tran\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
